'use client';

import { useCallback } from 'react';

interface PrintData {
  title: string;
  inputs: Record<string, string | number>;
  results: Record<string, string | number>;
  notes?: string[];
}

export function usePrintExport() {
  const print = useCallback((data: PrintData) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(generatePrintHTML(data));
    printWindow.document.close();
    printWindow.print();
  }, []);

  const copyToClipboard = useCallback(async (data: PrintData) => {
    const text = generateTextSummary(data);
    await navigator.clipboard.writeText(text);
    return text;
  }, []);

  return { print, copyToClipboard };
}

function generatePrintHTML(data: PrintData): string {
  return `<!DOCTYPE html><html><head><title>${data.title}</title>
<style>body{font-family:Arial,sans-serif;padding:20px;max-width:600px;margin:0 auto}
h1{color:#1e40af;border-bottom:2px solid #1e40af;padding-bottom:10px}
table{width:100%;border-collapse:collapse;margin:20px 0}
td{padding:10px;border-bottom:1px solid #e5e5e5}
.results{background:#f0fdf4;border:1px solid #22c55e;border-radius:8px;padding:15px;margin:20px 0}
.footer{margin-top:30px;font-size:12px;color:#737373}</style></head>
<body><h1>${data.title}</h1>
<h2>Inputs</h2><table>${Object.entries(data.inputs).map(([k,v])=>`<tr><td>${k}</td><td>${v}</td></tr>`).join('')}</table>
<div class="results"><h2>Results</h2><table>${Object.entries(data.results).map(([k,v])=>`<tr><td>${k}</td><td><strong>${v}</strong></td></tr>`).join('')}</table></div>
<div class="footer">WireSizes.com | ${new Date().toLocaleDateString()}</div></body></html>`;
}

function generateTextSummary(data: PrintData): string {
  return `${data.title}\n\nINPUTS:\n${Object.entries(data.inputs).map(([k,v])=>`${k}: ${v}`).join('\n')}\n\nRESULTS:\n${Object.entries(data.results).map(([k,v])=>`${k}: ${v}`).join('\n')}\n\nGenerated by WireSizes.com`;
}